---

- name: create CA Cert
  block:
  - name: create dir at localhost for keys
    file:
      path: "/tmp/ca"
      state: directory

  - name: create private key for CA
    openssl_privatekey:
      path: "{{ ca_path.key }}"
      size: 4096
      state: "present"
      type: "RSA"
      force: true

  - name: create CSR
    openssl_csr:
      path: "{{ ca_path.csr }}"
      privatekey_path: "{{ ca_path.key }}"
      state: "present"
      force: true
      key_usage:
        - keyCertSign
        - cRLSign
        - digitalSignature
      basic_constraints:
        - 'CA:TRUE'
      common_name: "{{ ca_csr.cn }}"
      country_name: "{{ ca_csr.c }}"
      email_address: "{{ ca_csr.e }}"
      organization_name: "{{ ca_csr.o }}"
      organizational_unit_name: "{{ ca_csr.ou }}"

  - name: generate selfsigned crt
    openssl_certificate:
      path: "{{ ca_path.pub }}"
      privatekey_path: "{{ ca_path.key }}"
      csr_path: "{{ ca_path.csr }}"
      provider: selfsigned
  when: need_CA |bool
  delegate_to: localhost
  run_once: true

