---

# 1. if need selfsigned certificate
# 1.1 create dir at localhost for root CA files
# 1.2 generate private key, csr and certificate on localhost
# 2.1 create directory for service
# 2.2 generate private key, csr and signed by root CA certificate
# 2.1 generate certificate chain bundle for service to use it for authentification (only public info)
# 3. copy private key, signed certificate and chain bundle of service to the remote host

# 1
- include: ca.yml

# 2-3
- include: service.yml
