---

- name: create private key for service
  openssl_privatekey:
    mode: 0640
#    owner: krol
#    group: krol
    path: "{{ service_path.key }}"
    size: 4096
    state: "present"
    type: "RSA"
    force: true
#  become: true

- name: create CSR for service
  openssl_csr:
    path: "{{ service_path.csr }}"
    privatekey_path: "{{ service_path.key }}"
    state: "present"
    force: true
    subject_alt_name: "DNS:{{ ansible_fqdn }},IP:{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    extended_key_usage:
      - clientAuth
      - serverAuth
    common_name: "{{ service_csr.cn }}"
    country_name: "{{ service_csr.c }}"
    email_address: "{{ service_csr.e }}"
    organization_name: "{{ service_csr.o }}"
    organizational_unit_name: "{{ service_csr.ou }}"

- name: sign our cert by CA
  openssl_certificate:
    path: "{{ service_path.pub }}"
    csr_path: "{{ service_path.csr }}"
    ownca_path: "{{ ca_path.pub }}"
    ownca_privatekey_path: "{{ ca_path.key }}"
    provider: ownca

- name: create chain bundle
  certificate_complete_chain:
    input_chain: "{{ lookup('file', '{{ service_path.pub }}') }}"
    root_certificates: "{{ ca_path.pub }}"
  register: chain_bundle

- name: copy complete chain to disk
  copy:
    dest: "{{ service_path.chain }}"
    content: "{{ ''.join(chain_bundle.complete_chain) }}"

